name: Java Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - uses: actions/checkout@v3

      # 2. Installer Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Build le projet avec Maven
      - name: Build with Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test
