name: Java Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - uses: actions/checkout@v3

      # 2. Installer Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Vérifier les droits d'exécution sur le wrapper
      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      # 4. Build le projet avec Gradle
      - name: Build with Gradle
        run: ./gradlew build
